FROM ruby:2.6.2-alpine3.9

RUN apk add --no-cache \
  libffi-dev \
  ca-certificates \
  build-base \
  sqlite-dev \
  nodejs \
  postgresql-dev \
  yarn

RUN mkdir -p /app
WORKDIR /app
EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
