version: "3"
services:
  postgres:
    image: postgres
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    env_file:
      - .env.dev-docker
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
      - yarn_cache:/usr/local/share/.cache/yarn/v4/
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
  mail-catcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
  worker:
    env_file:
      - .env.dev-docker
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
      - yarn_cache:/usr/local/share/.cache/yarn/v4/
    links:
      - postgres
      - redis
  webpack:
    env_file:
      - .env.dev-docker
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
      - yarn_cache:/usr/local/share/.cache/yarn/v4/
  redis:
    image: redis
    ports:
      - 6379
      - "3035:3035"
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
  bundler_gems:
  yarn_cache:
